### ISSUE TITLE
Test whether SGFC leaks memory

### ISSUE THREAD

**Issue by herzbube** [herzbube/libsgfcplusplus#3]
SGFC was conceived as a command line utility so it doesn't have to be religious in freeing memory.

It's currently not clear how such a test could be done.

**Comment by arno-h** [comment]
For what it's worth: I've run sgfc with valgrind on test files and other files, and valgrind reports no memory leak (the last leak detected was fixed in commit a1c1faa4)

**Comment by herzbube** [comment]
@arno-h Good to know, thanks. Sounds more thorough than anything I'm likely to do anytime soon. Closing.
